### ISSUE TITLE
Default `semgrep` install can still fail tests

### ISSUE THREAD

**Issue by Pamplemousse** [pixee/simple-gradle-codemod-tutorial#17]
In my case, running tests doesn't work unless `PYTHONPATH=$HOME/<subpath-to-python-libs-folder>` is prepended to the `./gradlew check` command.
As documented in https://github.com/pixee/codemodder-java/blob/c224b9ad0596fe08e9ae8cc2f45469b92364be1c/README.md?plain=1#L33-L45 .

**Comment by Pamplemousse** [comment]
Also needed when running the generated binary:

```shell
$ ./app/bin/app --dry-run ~/Workspace/target
codemodder: java/0.94.0
Sep 10, 2024 11:40:36 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.RuntimeException: error code seen from semgrep execution: 2
java.lang.RuntimeException: error code seen from semgrep execution: 2
        at io.codemodder.providers.sarif.semgrep.DefaultSemgrepRunner.run(DefaultSemgrepRunner.java:80)
        at io.codemodder.providers.sarif.semgrep.SemgrepModule.configure(SemgrepModule.java:152)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
        at com.google.inject.spi.Elements.getElements(Elements.java:108)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at io.codemodder.CodemodLoader.<init>(CodemodLoader.java:115)
        at io.codemodder.CLI.call(CLI.java:397)
        at io.codemodder.CLI.call(CLI.java:44)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.codemodder.Runner.run(Runner.java:34)
        at io.codemodder.Runner.run(Runner.java:44)
        at io.codemodder.sample.App.main(App.java:14)
```
